# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-09 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_generator_hierarchial',
            name='HL01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_hierarchial',
            name='HL02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_hierarchial',
            name='HL03',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_i_mea',
            name='MEA01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_i_mea',
            name='MEA02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_i_mea',
            name='MEA03',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_i_mea',
            name='MEA04',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='BST01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='BST02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='BST03',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='BST04',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='DTM01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='DTM02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='DTM03',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='DTM04',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='DTM05',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='MEA01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='MEA02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='MEA03',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='MEA04',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='NAME',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='REF01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='REF02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='ST01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='ST02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='TD101',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='TD102',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='TD301',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='TD303',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='TD501',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='TD502',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='TD503',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='TD504',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_name',
            name='N101',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_name',
            name='N103',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_name',
            name='N104',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_refi',
            name='REF01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_refi',
            name='REF02',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
