# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_generator_hierarchial',
            name='SN102',
            field=models.IntegerField(blank=True),
        ),
    ]
