# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-26 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_generator_master',
            name='TD401',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='TD402',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='TD403',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
