# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0002_auto_20160824_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_generator_hierarchial',
            name='SN102',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
