# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-26 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0003_remove_data_generator_hierarchial_prim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_generator_master',
            name='CLD01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='CLD02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='CLD03',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='CTT01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='CTT02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='ETD01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='ETD02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='ETD03',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='LIN02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='LIN03',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='SE01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='SE02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='SN102',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='SN103',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_generator_master',
            name='SN104',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
