# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-26 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0005_data_generator_hierarchial_prim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_generator_hierarchial',
            name='PRIM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_generator.Data_Generator_Master'),
        ),
    ]
