# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0008_auto_20160727_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_generator_hierarchial',
            name='PRIM',
        ),
    ]
