# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0011_auto_20160727_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_generator_hierarchial',
            name='CLD01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_generator_hierarchial',
            name='CLD02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_generator_hierarchial',
            name='CLD03',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
