# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_segments_ATH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATH_0', models.CharField(blank=True, max_length=50)),
                ('ATH_1', models.CharField(blank=True, max_length=50)),
                ('ATH_2', models.CharField(blank=True, max_length=50)),
                ('ATH_3', models.CharField(blank=True, max_length=50)),
                ('ATH_4', models.CharField(blank=True, max_length=50)),
                ('ATH_5', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='data_segments_master',
            name='PER_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_master',
            name='PER_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_master',
            name='PER_3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_master',
            name='PER_4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_master',
            name='REF_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_master',
            name='REF_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_ath',
            name='prim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_mining.data_segments_master'),
        ),
    ]
