# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='edi_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edi_name', models.CharField(max_length=50)),
                ('edi_file', models.FileField(upload_to='media/edi/')),
            ],
        ),
    ]
