# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-18 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_segments_862LIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LIN_1', models.CharField(blank=True, max_length=50)),
                ('LIN_2', models.CharField(blank=True, max_length=50)),
                ('LIN_3', models.CharField(blank=True, max_length=50)),
                ('LIN_4', models.CharField(blank=True, max_length=50)),
                ('LIN_5', models.CharField(blank=True, max_length=50)),
                ('LIN_6', models.CharField(blank=True, max_length=50)),
                ('LIN_7', models.CharField(blank=True, max_length=50)),
                ('LIN_8', models.CharField(blank=True, max_length=50)),
                ('LIN_9', models.CharField(blank=True, max_length=50)),
                ('LIN_10', models.CharField(blank=True, max_length=50)),
                ('LIN_11', models.CharField(blank=True, max_length=50)),
                ('LIN_12', models.CharField(blank=True, max_length=50)),
                ('LIN_13', models.CharField(blank=True, max_length=50)),
                ('LIN_14', models.CharField(blank=True, max_length=50)),
                ('LIN_15', models.CharField(blank=True, max_length=50)),
                ('prim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_mining.data_segments_master')),
            ],
        ),
        migrations.CreateModel(
            name='data_segments_BSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BSS_1', models.CharField(blank=True, max_length=50)),
                ('BSS_2', models.CharField(blank=True, max_length=50)),
                ('BSS_3', models.CharField(blank=True, max_length=50)),
                ('BSS_4', models.CharField(blank=True, max_length=50)),
                ('BSS_5', models.CharField(blank=True, max_length=50)),
                ('BSS_6', models.CharField(blank=True, max_length=50)),
                ('BSS_7', models.CharField(blank=True, max_length=50)),
                ('BSS_8', models.CharField(blank=True, max_length=50)),
                ('BSS_11', models.CharField(blank=True, max_length=50)),
                ('prim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_mining.data_segments_master')),
            ],
        ),
    ]
