# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0002_edi_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edi_address',
            name='edi_file',
            field=models.FileField(upload_to='edi/'),
        ),
    ]
