# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0002_auto_20160711_1515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modelo',
            new_name='Modelo_GS',
        ),
    ]
