# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0002_auto_20160712_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_segments_master',
            name='CT_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_master',
            name='CT_2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
