# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0003_auto_20160711_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_segments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GS_1', models.CharField(blank=True, max_length=50)),
                ('GS_2', models.CharField(blank=True, max_length=50)),
                ('GS_3', models.CharField(blank=True, max_length=50)),
                ('GS_4', models.CharField(blank=True, max_length=50)),
                ('GS_5', models.CharField(blank=True, max_length=50)),
                ('GS_6', models.CharField(blank=True, max_length=50)),
                ('GS_7', models.CharField(blank=True, max_length=50)),
                ('GS_8', models.CharField(blank=True, max_length=50)),
                ('ST_1', models.CharField(blank=True, max_length=50)),
                ('ST_2', models.CharField(blank=True, max_length=50)),
                ('ST_3', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Modelo_GS',
        ),
    ]
