# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0004_auto_20160712_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_segments_master',
            name='GE_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_master',
            name='GE_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_master',
            name='IEA_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_master',
            name='IEA_2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
