# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-03 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0005_auto_20160802_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_segments_master',
            name='DTM_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_master',
            name='DTM_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_master',
            name='DTM_3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_n',
            name='N3_0',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_n',
            name='N3_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_n',
            name='N4_0',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_n',
            name='N4_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_n',
            name='N4_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='data_segments_n',
            name='N4_3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
