# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-03 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0006_auto_20160803_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_segments_SHP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHP_1', models.CharField(blank=True, max_length=50)),
                ('SHP_2', models.CharField(blank=True, max_length=50)),
                ('SHP_3', models.CharField(blank=True, max_length=50)),
                ('SHP_4', models.CharField(blank=True, max_length=50)),
                ('SHP_5', models.CharField(blank=True, max_length=50)),
                ('SHP_6', models.CharField(blank=True, max_length=50)),
                ('SHP_7', models.CharField(blank=True, max_length=50)),
                ('prim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_mining.data_segments_master')),
            ],
        ),
    ]
