# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0007_data_segments_shp'),
        ('data_mining', '0004_auto_20160715_1239'),
    ]

    operations = [
    ]
